# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
  oauth_redirect_uri: '%env(OAUTH_REDIRECT_URI)%'
  oauth_connect_uri: '%env(OAUTH_CONNECT_URI)%'
  oauth_socials: [ 'google', 'vk' ]

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
      - '../src/Tests/'

  App\Service\RefreshTokenService:
    arguments:
      $refreshTokenManager: '@gesdinet.jwtrefreshtoken.refresh_token_manager'
      $refreshTokenParameterName: '%gesdinet_jwt_refresh_token.token_parameter_name%'
      $ttl: '%env(int:REFRESH_TOKEN_TTL)%'

  App\Resolver\RequestDTOResolver:
    arguments:
      - '@validator'
    tags:
      - { name: controller.request_value_resolver, priority: 50 }